import {createFloodSurfaces,updateFloodSurfaces,channelHeight} from './flood.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {applyEstateMaterials,outdoorEnvironment} from './materials.js';
import {translateCamera,configureNavigation,streetViews} from './navigation.js';
import {sections,devices,colours,simulatedSnapshot} from './network.js';
const $=id=>document.getElementById(id),mobile=()=>innerWidth<=760,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const state={scenario:'normal',time:0,paused:reduced,selection:null,mode:'explore',navigation:'move',tourTime:0,layers:{drains:true,devices:true,flow:true,risk:true}};
let renderer,scene,camera,controls,composer,ssao,estate,deviceTemplate,deviceView,flight=null,last=0,uiClock=0,markerClock=0,ready=false,frameHandle;
const drainage=new THREE.Group(),hardware=new THREE.Group(),flowGroup=new THREE.Group(),riskGroup=new THREE.Group(),waters=[],streams=[],markers=[];let pools=[];
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),v3=new THREE.Vector3();
const snapshot=()=>simulatedSnapshot(state.scenario,state.time);
const materials={steel:new THREE.MeshStandardMaterial({color:'#505e63',metalness:.7,roughness:.5}),mount:new THREE.MeshStandardMaterial({color:'#a6b1ac',metalness:.25,roughness:.8})};
function mesh(geo,mat,parent,x,y,z){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function bar(parent,a,b,r,mat){const m=mesh(new THREE.CylinderGeometry(r,r,a.distanceTo(b),8),mat,parent,0,0,0);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());return m}
function sceneEnvironment(target,render){const room=new RoomEnvironment(),pmrem=new THREE.PMREMGenerator(render);target.environment=pmrem.fromScene(room,.06).texture;target.environmentIntensity=.45;room.dispose();pmrem.dispose()}
function overviewPose(){const target=new THREE.Vector3(6,0,1),position=new THREE.Vector3(150,120,182);if(mobile()){const rect=$('scene').getBoundingClientRect(),aspect=rect.width/Math.max(1,rect.height);const vertical=THREE.MathUtils.degToRad(55),horizontal=2*Math.atan(Math.tan(vertical/2)*aspect);const distance=88/Math.sin(Math.min(vertical,horizontal)/2);position.sub(target).normalize().multiplyScalar(distance).add(target)}return {position,target}}
function fly(position,target,duration=1.7){flight={from:camera.position.clone(),fromTarget:controls.target.clone(),position:position.clone(),target:target.clone(),t:0,duration:reduced?.01:duration}}
function resetCamera(){const p=overviewPose();fly(p.position,p.target);closeInspector()}
function focusAsset(type,id){const a=type==='device'?devices.find(a=>a.id===id):sections.find(a=>a.id===id);const x=type==='device'?a.x:(a.from.x+a.to.x)/2,z=type==='device'?a.z:(a.from.z+a.to.z)/2;fly(new THREE.Vector3(x+36,35,z+49),new THREE.Vector3(x,1,z));}
function selectAsset(type,id,focus=true){closeMobilePanels();state.selection={type,id};$('inspector').hidden=false;document.body.classList.add('has-selection');$('asset-select').value=type+':'+id;$('inspect-device').hidden=type!=='device';for(const m of markers)m.button.classList.toggle('active',type==='device'&&m.device.id===id);if(focus)focusAsset(type,id);updateUI()}
function closeInspector(){state.selection=null;$('inspector').hidden=true;document.body.classList.remove('has-selection');$('asset-select').value='';for(const m of markers)m.button.classList.remove('active')}
function makeWater(){
for(const s of sections){const dx=s.to.x-s.from.x,dz=s.to.z-s.from.z,len=Math.hypot(dx,dz),angle=Math.atan2(dx,dz);const mat=new THREE.MeshStandardMaterial({color:'#3e9eaf',emissive:'#164c60',emissiveIntensity:.35,metalness:.3,roughness:.22,transparent:true,opacity:.92});const m=mesh(new THREE.BoxGeometry(s.width,.08,len),mat,drainage,(s.from.x+s.to.x)/2,.2,(s.from.z+s.to.z)/2);m.rotation.y=angle;m.userData.section=s.id;m.castShadow=false;waters.push({mesh:m,section:s});
const count=Math.max(2,Math.floor(len/7));const markerGeometry=new THREE.ConeGeometry(.22,.7,3);markerGeometry.rotateX(Math.PI/2);const markerMaterial=new THREE.MeshBasicMaterial({color:'#a2edff',transparent:true,opacity:.8});for(let i=0;i<count;i++){const arrow=new THREE.Mesh(markerGeometry,markerMaterial);arrow.rotation.y=angle;flowGroup.add(arrow);streams.push({mesh:arrow,section:s,phase:i/count})}

}
const canal=mesh(new THREE.BoxGeometry(6.7,.1,142),new THREE.MeshStandardMaterial({color:'#286a79',roughness:.17,metalness:.42}),scene,84,-1.55,0);canal.castShadow=false;
const fall=mesh(new THREE.PlaneGeometry(2.8,1.7),new THREE.MeshStandardMaterial({color:'#70bac8',transparent:true,opacity:.7,side:THREE.DoubleSide,roughness:.2}),drainage,84.1,-.65,53);fall.rotation.y=Math.PI/2;
scene.add(drainage,hardware,flowGroup,riskGroup);pools=createFloodSurfaces(sections,drainage);
}
let obstruction, rainPoints, rainPositions, rainGeometry;
function makeWeather(){
obstruction=new THREE.Group();const rubbleMat=new THREE.MeshStandardMaterial({color:'#8c7761',roughness:1});for(let i=0;i<9;i++){const m=mesh(new THREE.DodecahedronGeometry(.4+(i%3)*.13),rubbleMat,obstruction,62+(i%3-1)*.65,.48,17+Math.floor(i/3)*.45);m.rotation.set(i,.4*i,.2*i)}scene.add(obstruction);obstruction.visible=false;
rainGeometry=new THREE.BufferGeometry();rainPositions=new Float32Array(1000*6);for(let i=0;i<1000;i++){const j=i*6,x=((i*73.31)%160)-80,y=(i*29.27)%75,z=((i*43.57)%140)-70;rainPositions.set([x,y,z,x-.2,y-1.3,z],j)}rainGeometry.setAttribute('position',new THREE.BufferAttribute(rainPositions,3));rainPoints=new THREE.LineSegments(rainGeometry,new THREE.LineBasicMaterial({color:'#b0d8e9',transparent:true,opacity:.35,depthWrite:false}));rainPoints.frustumCulled=false;scene.add(rainPoints);rainPoints.visible=false;
}
function makeDeviceInstances(){
const bounds=new THREE.Box3().setFromObject(deviceTemplate),centre=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());deviceTemplate.position.sub(centre);const normalised=new THREE.Group();normalised.add(deviceTemplate);normalised.scale.setScalar(1/size.y);deviceTemplate=normalised;
for(const d of devices){const unit=deviceTemplate.clone(true);unit.scale.multiplyScalar(1.1);unit.position.set(d.x,2.35,d.z);unit.rotation.y=Math.PI;unit.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.device=d.id}});hardware.add(unit);
// Source GLB front is +X. Rotate it away from the pole (+X in estate space).
// Rear plate sits at x=0.266 after normalisation; support stops behind it.
bar(hardware,new THREE.Vector3(d.x+1.35,.55,d.z),new THREE.Vector3(d.x+1.35,2.75,d.z),.065,materials.steel);
bar(hardware,new THREE.Vector3(d.x+1.35,2.29,d.z),new THREE.Vector3(d.x+.30,2.29,d.z),.055,materials.steel);
// Backing bracket meets the existing rear plate without entering the enclosure.
mesh(new THREE.BoxGeometry(.035,.34,.30),materials.steel,hardware,d.x+.283,2.29,d.z);
for(const y of [-.12,.12])for(const z of [-.10,.10]){
const bolt=mesh(new THREE.CylinderGeometry(.018,.018,.025,6),materials.mount,hardware,d.x+.31,2.29+y,d.z+z);bolt.rotation.z=Math.PI/2;
}
mesh(new THREE.BoxGeometry(.55,.25,.55),materials.mount,hardware,d.x+1.35,.5,d.z);
const button=document.createElement('button');button.className='marker';button.setAttribute('aria-label',`Inspect Sentinel ${d.id}, ${d.name}`);button.innerHTML=`<span>${d.id}</span>`;button.addEventListener('click',()=>{setMode('explore');selectAsset('device',d.id)});$('markers').append(button);markers.push({button,device:d,position:new THREE.Vector3(d.x,3.35,d.z)});
}
}
function makeSign(){const c=document.createElement('canvas');c.width=1024;c.height=128;const g=c.getContext('2d');g.fillStyle='#dad8c8';g.fillRect(0,0,1024,128);g.fillStyle='#31424a';g.textAlign='center';g.font='500 55px Arial';g.fillText('AZURE GARDENS',512,86);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=mesh(new THREE.PlaneGeometry(12,1.5),new THREE.MeshStandardMaterial({map:t,roughness:.8}),scene,0,5.2,63.62);m.castShadow=false;}
function updateMarkers(){if(!camera)return;const rect=$('scene').getBoundingClientRect();for(const m of markers){const p=m.position.clone().project(camera);const px=(p.x*.5+.5)*rect.width,py=(-p.y*.5+.5)*rect.height;const visible=state.layers.devices&&p.z>-1&&p.z<1&&px>65&&px<rect.width-65&&py>65&&py<rect.height-20;m.button.hidden=!visible;if(visible){m.button.style.left=((p.x*.5+.5)*rect.width)+'px';m.button.style.top=((-p.y*.5+.5)*rect.height)+'px'}}}
let sunlight,ambient;
async function init(){
renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,$('app').clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.outputColorSpace=THREE.SRGBColorSpace;$('scene').append(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','3D estate. Move mode: drag or scroll to travel. Orbit mode: drag to rotate. Arrow keys or WASD move; plus and minus zoom; zero resets.');
scene=new THREE.Scene();scene.background=new THREE.Color(document.documentElement.dataset.theme==='light'?'#fafafa':'#0b0c0e');scene.fog=new THREE.Fog(scene.background,500,850);camera=new THREE.PerspectiveCamera(mobile()?55:39,innerWidth/$('app').clientHeight,.25,1000);const pose=overviewPose();camera.position.copy(pose.position);controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(pose.target);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=8;controls.maxDistance=440;controls.maxPolarAngle=Math.PI*.47;controls.minPolarAngle=.12;controls.panSpeed=1;controls.zoomSpeed=.65;configureNavigation(controls,state.navigation);controls.update();controls.addEventListener('start',()=>{flight=null;if(state.mode==='presentation')setMode('explore')});
ambient=new THREE.HemisphereLight('#d9e8f3','#6c7562',.7);scene.add(ambient);sunlight=new THREE.DirectionalLight('#fff0d9',2.5);sunlight.position.set(-75,120,60);sunlight.castShadow=true;sunlight.shadow.mapSize.set(mobile()?2048:4096,mobile()?2048:4096);Object.assign(sunlight.shadow.camera,{left:-110,right:110,top:110,bottom:-110,near:1,far:300});sunlight.shadow.bias=-.0002;sunlight.shadow.normalBias=.035;sunlight.shadow.radius=3;scene.add(sunlight);outdoorEnvironment(scene,renderer);
const loader=new GLTFLoader();const [estateGLB,sentinelGLB]=await Promise.all([loader.loadAsync('./assets/estate.glb'),loader.loadAsync('./assets/sentinel.glb')]);estate=estateGLB.scene;estate.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});await applyEstateMaterials(estate,renderer);scene.add(estate);deviceTemplate=sentinelGLB.scene;makeWater();makeWeather();makeDeviceInstances();makeSign();
// SSAO adds contact shading between roofs, facades and landscaping.
composer=new EffectComposer(renderer);ssao=new SSAOPass(scene,camera,Math.round(innerWidth*.75),Math.round($('app').clientHeight*.75),16);ssao.kernelRadius=1.7;ssao.minDistance=.0001;ssao.maxDistance=.006;composer.addPass(new RenderPass(scene,camera));composer.addPass(ssao);composer.addPass(new OutputPass());
renderer.shadowMap.needsUpdate=true;ready=true;setSceneControls(true);resize();$('loading').hidden=true;bindCanvas();updateUI();frameHandle=requestAnimationFrame(frame);
}
function resize(){if(!renderer||!camera)return;const w=$('scene').clientWidth,h=$('scene').clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.fov=mobile()?55:39;camera.updateProjectionMatrix();renderer.setSize(w,h);composer?.setSize(w,h);if(deviceView&&$('device-dialog').open)resizeDevice();}
window.addEventListener('resize',resize);
function changeScenario(value,fromTour=false){if(value===state.scenario)for(const p of pools)p.level=0;state.scenario=value;state.time=0;if(!fromTour){setMode('explore');state.paused=false}for(const b of document.querySelectorAll('[data-scenario]')){const active=b.dataset.scenario===value;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))}obstruction.visible=value==='blocked'&&state.layers.drains;rainPoints.visible=value==='rain';sunlight.intensity=value==='rain'?1.2:2.5;ambient.intensity=value==='rain'?.85:.7;renderer.shadowMap.needsUpdate=true;if(!fromTour){if(value==='blocked')selectAsset('device','FG-027');else{closeInspector();const p=overviewPose();fly(p.position,p.target)}}updateUI()}
function updateUI(){updateStageProgress();const s=snapshot(),risk=s.risk,c=risk>=65?colours.critical:risk>=35?colours.elevated:colours.healthy;$('risk').innerHTML=`${risk}<small>/100</small>`;$('risk').style.color=c;$('rain').innerHTML=`${s.rainfall}<small>mm/h</small>`;$('health').textContent=s.health+'% drainage health';$('simulation-time').textContent=`${String(Math.floor(state.time/60)).padStart(2,'0')}:${String(Math.floor(state.time%60)).padStart(2,'0')}`;$('pause').textContent=state.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',state.paused?'Play simulation':'Pause simulation');
const blocked=state.scenario==='blocked',raining=state.scenario==='rain';$('scenario-caption').textContent=blocked?(state.time>9?'Water overflowing onto nearby streets':'Water building upstream of blockage'):raining?(state.time>12?'Water spilling onto estate roads':'Rainfall building across the estate'):'Water moving towards the outfall';
$('insight-copy').textContent=blocked?(state.time<6?'Flow is slowing at the east collector. Comparing upstream and downstream readings.':state.time<14?'Water is backing up from FG-027 into connected upstream channels.':'The east collector is obstructed. The central collector and low-lying east garden are at risk.'):raining?(state.time<8?'Rainfall is increasing. Tracking rising levels across the network.':'Collector levels are elevated. Watch the east garden and outfall capacity.'):'All drainage sections are operating within normal capacity.';
$('action').hidden=!(blocked&&state.time>6||raining&&state.time>12);$('action').textContent=blocked?'Recommended: dispatch a crew to clear the east collector at FG-027.':'Recommended: inspect inlet debris and keep the outfall clear.';
$('alert-banner').hidden=!(blocked&&state.time>6);$('alert-title').textContent=state.time<14?'Elevated water detected':'Critical blockage detected';$('alert-copy').textContent='East collector · FG-027 · '+s.alerts+' active alerts';
if(state.selection){const {type,id}=state.selection,a=type==='device'?devices.find(d=>d.id===id):sections.find(s=>s.id===id),r=type==='device'?s.devices[id]:s.sections[id];$('asset-type').textContent=type==='device'?'SENTINEL V1':'DRAINAGE SECTION';$('asset-name').textContent=type==='device'?'Sentinel '+id:id+' · Drainage';$('asset-location').textContent=a.name;$('asset-status').textContent=type==='device'?'Online':'Connected';$('water').innerHTML=r.water+'<small>%</small>';$('silt').innerHTML=r.silt+'<small>%</small>';$('flow').innerHTML=r.flow.toFixed(2)+'<small>m³/s</small>';$('asset-risk').textContent=r.risk==='healthy'?'Low risk':r.risk==='elevated'?'Elevated risk':'Critical risk';$('asset-risk').style.color=colours[r.risk];$('reading-time').textContent='Updated '+Math.floor(state.time-r.observedAt)+'s ago · Simulated';}
for(const m of markers){const r=s.devices[m.device.id],colour=colours[r.risk];m.button.style.setProperty('--marker-color',colour);m.button.style.borderColor=colour}
}
const tourSteps=[{at:0,scenario:'normal',title:'One network. Complete visibility.',copy:'Eight Sentinels watch water move from the upstream drains to the estate’s primary outfall.',label:'01 / THE CONNECTED ESTATE',position:[145,113,175],target:[6,0,1]}, {at:12,scenario:'rain',title:'Conditions change. FlowGuard sees it.',copy:'Rainfall builds across the estate. Water levels rise, and the collector becomes the first area to watch.',label:'02 / HEAVY RAINFALL',position:[116,87,75],target:[24,1,-5]}, {at:30,scenario:'blocked',title:'A local blockage. A wider impact.',copy:'At FG-027, flow slows. Water backs into the central collector and neighbouring drainage sections.',label:'03 / THE NETWORK EFFECT',position:[111,49,73],target:[58,1,12]}, {at:48,scenario:'blocked',title:'From detection to intervention.',copy:'Noah OS flags the affected location and recommends a crew to clear it, before more of the estate is affected.',label:'04 / ACT WITH CONTEXT',position:[101,37,65],target:[62,1,18]}];let tourStep=-1;
function setMode(mode){closeMobilePanels();if(mode==='explore'&&state.mode==='presentation')flight=null;state.mode=mode;$('presentation').classList.toggle('active',mode==='presentation');$('explore').classList.toggle('active',mode==='explore');$('presentation').setAttribute('aria-pressed',String(mode==='presentation'));$('explore').setAttribute('aria-pressed',String(mode==='explore'));$('story').hidden=mode!=='presentation';document.body.classList.toggle('touring',mode==='presentation');if(mode==='presentation'){state.tourTime=0;tourStep=-1;state.paused=false;closeInspector();$('layers-panel').hidden=true;$('layers-btn').setAttribute('aria-expanded','false');}else tourStep=-1;updateStageProgress();}
function updateStageProgress(){
if(state.mode!=='presentation')return;
const stages=[
{id:'normal',start:tourSteps[0].at,end:tourSteps[1].at,label:'Monitoring drainage…',name:'Normal flow'},
{id:'rain',start:tourSteps[1].at,end:tourSteps[2].at,label:'Rainfall rising…',name:'Heavy rainfall'},
{id:'blocked',start:tourSteps[2].at,end:60,label:'Tracking water buildup…',name:'Blocked drain'}
];
const t=state.tourTime;
for(const stage of stages){
const percent=Math.round(THREE.MathUtils.clamp((t-stage.start)/(stage.end-stage.start),0,1)*100),el=$('stage-'+stage.id),done=t>=stage.end;
el.style.setProperty('--stage-progress',percent+'%');el.classList.toggle('complete',done);el.classList.toggle('current',t>=stage.start&&!done);el.textContent=done?'✓':'';el.setAttribute('aria-valuenow',String(percent));el.title=stage.name+' · '+(done?'Complete':percent+'%');}
const active=stages.find(stage=>t<stage.end)||stages[2];
const text=t>=60?'Presentation complete':state.paused?'Paused · '+active.name:active.label;
if($('stage-status').textContent!==text)$('stage-status').textContent=text;
}
function updateTour(dt){if(state.mode!=='presentation')return;state.tourTime+=dt;let index=0;for(let i=0;i<tourSteps.length;i++)if(state.tourTime>=tourSteps[i].at)index=i;if(index!==tourStep){tourStep=index;const step=tourSteps[index];if(index!==3)changeScenario(step.scenario,true);$('story-step').textContent=step.label;$('story-title').textContent=step.title;$('story-copy').textContent=step.copy;const pos=new THREE.Vector3(...step.position),target=new THREE.Vector3(...step.target);if(mobile()&&index===0){const pose=overviewPose();pos.copy(pose.position);target.copy(pose.target)}fly(pos,target,3)}$('story-progress').style.width=Math.min(100,state.tourTime/60*100)+'%';if(state.tourTime>=60){state.paused=true;$('story-step').textContent='PRESENTATION COMPLETE';$('story-copy').textContent='Choose Explore to inspect the estate, or Presentation to replay the guided story.'}}
function frame(now){const dt=last?Math.min((now-last)/1000,.05):0;last=now;if(!state.paused&&!$('device-dialog').open){state.time+=dt;updateTour(dt)}if(flight){flight.t+=dt;const a=Math.min(flight.t/flight.duration,1),t=a*a*(3-2*a);camera.position.lerpVectors(flight.from,flight.position,t);controls.target.lerpVectors(flight.fromTarget,flight.target,t);if(a>=1)flight=null}controls.update();
const s=snapshot();for(const w of waters){const r={...s.sections[w.section.id]};if(!state.layers.risk)r.risk='healthy';w.mesh.position.y=channelHeight(r.water);w.mesh.material.color.set(r.risk==='healthy'?'#429fb4':colours[r.risk]);w.mesh.material.emissive.set(r.risk==='healthy'?'#143e4b':colours[r.risk]);w.mesh.material.emissiveIntensity=(state.selection?.type==='section'&&state.selection.id===w.section.id) ? .8 : (r.risk==='healthy' ? .2 : .12);w.mesh.material.opacity=state.selection?.type==='section'&&state.selection.id===w.section.id?1:.9;}
updateFloodSurfaces(pools,s,state.paused||$('device-dialog').open?0:dt,state.time);
for(const f of streams){const r=s.sections[f.section.id],t=(f.phase+state.time*r.flow*.025)%1;f.mesh.position.set(THREE.MathUtils.lerp(f.section.from.x,f.section.to.x,t),channelHeight(r.water)+.07,THREE.MathUtils.lerp(f.section.from.z,f.section.to.z,t));}
if(rainPoints.visible&&!state.paused&&!$('device-dialog').open){const a=rainGeometry.attributes.position.array;for(let i=0;i<a.length;i+=6){a[i+1]-=dt*31;a[i+4]-=dt*31;if(a[i+1]<0){a[i+1]=75;a[i+4]=73.7}}rainGeometry.attributes.position.needsUpdate=true;rainPoints.material.opacity=Math.min(.4,state.time/18*.4)}
uiClock+=dt;markerClock+=dt;if(uiClock>.25){updateUI();uiClock=0}if(markerClock>.025){updateMarkers();markerClock=0}if($('device-dialog').open&&deviceView){deviceView.controls.update();deviceView.renderer.render(deviceView.scene,deviceView.camera)}else{try{composer.render()}catch(error){console.error(error);showGraphicsError('The renderer encountered a graphics error. Reload to restore the scene.');return}}frameHandle=requestAnimationFrame(frame);}
function bindCanvas(){let down=null;const activePointers=new Set();
renderer.domElement.addEventListener('pointerdown',e=>{renderer.domElement.focus({preventScroll:true});activePointers.add(e.pointerId);down=activePointers.size===1&&e.button===0?{id:e.pointerId,x:e.clientX,y:e.clientY,time:performance.now(),moved:false}:null;});
renderer.domElement.addEventListener('pointermove',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)down.moved=true;});
renderer.domElement.addEventListener('pointercancel',e=>{activePointers.delete(e.pointerId);down=null;});renderer.domElement.addEventListener('pointerup',e=>{activePointers.delete(e.pointerId);const press=down;down=null;if(!press||press.id!==e.pointerId||press.moved||activePointers.size||Math.hypot(e.clientX-press.x,e.clientY-press.y)>5||performance.now()-press.time>600)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const obstructionDistance=raycaster.intersectObject(estate,true)[0]?.distance??Infinity;if(state.layers.devices){const hits=raycaster.intersectObject(hardware,true).filter(h=>h.object.userData.device&&h.distance<obstructionDistance);if(hits.length){setMode('explore');selectAsset('device',hits[0].object.userData.device);return}}if(state.layers.drains){const hits=raycaster.intersectObjects(waters.map(w=>w.mesh)).filter(h=>h.distance<obstructionDistance);if(hits.length){setMode('explore');selectAsset('section',hits[0].object.userData.section)}}});renderer.domElement.addEventListener('keydown',e=>{
const key=e.key.toLowerCase();
if(!['arrowleft','arrowright','arrowup','arrowdown','w','a','s','d','+','=','-','0'].includes(key))return;
e.preventDefault();setMode('explore');flight=null;
if(key==='0')return resetCamera();
if(['+','=','-'].includes(key))return zoomCamera(key==='-'?1.15:1/1.15);
const step=Math.max(.8,Math.min(6,camera.position.distanceTo(controls.target)*.035));
translateCamera(camera,controls,['arrowleft','a'].includes(key)?-step:['arrowright','d'].includes(key)?step:0,['arrowup','w'].includes(key)?step:['arrowdown','s'].includes(key)?-step:0);
});
renderer.domElement.addEventListener('wheel',e=>{
if(state.navigation!=='move'||!ready)return;
e.preventDefault();e.stopImmediatePropagation();setMode('explore');flight=null;
if(e.ctrlKey){zoomCamera(Math.exp(THREE.MathUtils.clamp(e.deltaY,-100,100)*.008),false);return;}
const units=e.deltaMode===1?16:e.deltaMode===2?$('app').clientHeight:1;
const speed=Math.max(.006,camera.position.distanceTo(controls.target)/900);
translateCamera(camera,controls,e.deltaX*units*speed,-e.deltaY*units*speed);
},{passive:false,capture:true});
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();showGraphicsError('The graphics connection was interrupted. Reload to restore the estate.')});}
function resizeDevice(){const host=$('device-scene'),w=host.clientWidth,h=host.clientHeight;deviceView.renderer.setSize(w,h);deviceView.camera.aspect=w/h;deviceView.camera.updateProjectionMatrix()}
async function openDevice(){if(!ready)return;$('device-dialog').showModal();if(!deviceView){const r=new THREE.WebGLRenderer({antialias:true,alpha:false});r.setPixelRatio(Math.min(devicePixelRatio,1.7));r.toneMapping=THREE.ACESFilmicToneMapping;r.toneMappingExposure=1.45;r.outputColorSpace=THREE.SRGBColorSpace;$('device-scene').append(r.domElement);const s=new THREE.Scene();s.background=new THREE.Color(document.documentElement.dataset.theme==='light'?'#f6f6f5':'#101112');s.add(new THREE.HemisphereLight('#d7edff','#687580',3));const key=new THREE.DirectionalLight('#fff0d9',4);key.position.set(3,4,5);s.add(key);const fill=new THREE.DirectionalLight('#86c8ef',2);fill.position.set(-3,2,-1);s.add(fill);sceneEnvironment(s,r);s.environmentIntensity=.7;const model=deviceTemplate.clone(true);s.add(model);const c=new THREE.PerspectiveCamera(35,1,.01,100);c.position.set(1.05,.45,1.75);const ctl=new OrbitControls(c,r.domElement);ctl.target.set(0,0,0);ctl.enableDamping=true;ctl.enablePan=false;ctl.minDistance=.8;ctl.maxDistance=4;ctl.update();deviceView={renderer:r,scene:s,camera:c,controls:ctl}}resizeDevice();}
for(const [title,type,items]of [['Sentinels','device',devices],['Drainage sections','section',sections]]){const group=document.createElement('optgroup');group.label=title;for(const a of items){const o=document.createElement('option');o.value=type+':'+a.id;o.textContent=a.id+' · '+a.name;group.append(o)}$('asset-select').append(group)}
$('asset-select').addEventListener('change',e=>{if(!e.target.value)return;const [type,id]=e.target.value.split(':');setMode('explore');selectAsset(type,id);$('layers-panel').hidden=true;$('layers-btn').setAttribute('aria-expanded','false')});
$('layers-btn').addEventListener('click',()=>{$('layers-panel').hidden=!$('layers-panel').hidden;$('layers-btn').setAttribute('aria-expanded',String(!$('layers-panel').hidden))});
for(const key of Object.keys(state.layers))$(key+'-toggle').addEventListener('change',e=>{state.layers[key]=e.target.checked;drainage.visible=state.layers.drains;hardware.visible=state.layers.devices;flowGroup.visible=state.layers.flow&&state.layers.drains;riskGroup.visible=state.layers.risk&&state.layers.drains;obstruction.visible=state.scenario==='blocked'&&state.layers.drains;estate.traverse(o=>{if(o.isMesh&&['Drain concrete','Channel bed'].includes(o.material.name))o.visible=state.layers.drains});updateMarkers();renderer.shadowMap.needsUpdate=true});
for(const b of document.querySelectorAll('[data-scenario]'))b.addEventListener('click',()=>{if(ready)changeScenario(b.dataset.scenario)});
$('presentation').addEventListener('click',()=>{if(ready)setMode('presentation')});$('explore').addEventListener('click',()=>{setMode('explore');state.paused=false});$('reset').addEventListener('click',()=>{setMode('explore');resetCamera()});$('close-inspector').addEventListener('click',closeInspector);$('locate-alert').addEventListener('click',()=>{setMode('explore');selectAsset('device','FG-027')});$('pause').addEventListener('click',()=>{state.paused=!state.paused;updateUI()});$('restart').addEventListener('click',()=>{if(state.mode==='presentation')setMode('presentation');else changeScenario(state.scenario)});
function zoomCamera(factor,animated=true){if(!ready)return;setMode('explore');flight=null;const o=camera.position.clone().sub(controls.target);o.setLength(THREE.MathUtils.clamp(o.length()*factor,8,440));if(animated)fly(controls.target.clone().add(o),controls.target,.2);else{camera.position.copy(controls.target).add(o);controls.update();}}
for(const [id,factor]of [['zoom-in',.8],['zoom-out',1.25]])$(id).addEventListener('click',()=>zoomCamera(factor));
function setNavigation(mode){state.navigation=mode;setMode('explore');flight=null;configureNavigation(controls,mode);for(const name of ['move','orbit']){$('nav-'+name).classList.toggle('active',name===mode);$('nav-'+name).setAttribute('aria-pressed',String(name===mode))}renderer.domElement.style.cursor=mode==='move'?'grab':'crosshair';}
for(const mode of ['move','orbit'])$('nav-'+mode).addEventListener('click',()=>{if(ready)setNavigation(mode)});
for(const v of streetViews){const option=document.createElement('option');option.value=v.id;option.textContent=v.name;$('street-select').append(option)}
$('street-select').addEventListener('change',e=>{const v=streetViews.find(v=>v.id===e.target.value);if(!ready||!v)return;setNavigation('move');closeInspector();fly(new THREE.Vector3(...v.position),new THREE.Vector3(...v.target));$('layers-panel').hidden=true;$('layers-btn').setAttribute('aria-expanded','false');e.target.value='';});
$('inspect-device').addEventListener('click',()=>openDevice().catch(error=>{console.error(error);$('device-dialog').close();showGraphicsError('The device viewer could not initialise. Reload to restore the scene.')}));$('close-device').addEventListener('click',()=>$('device-dialog').close());$('device-reset').addEventListener('click',()=>{deviceView.camera.position.set(1.05,.45,1.75);deviceView.controls.target.set(0,0,0);deviceView.controls.update()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('layers-panel').hidden=true;$('layers-btn').setAttribute('aria-expanded','false');if(!$('device-dialog').open)closeInspector()}});
function applyTheme(){const light=document.documentElement.dataset.theme==='light';$('theme-toggle').setAttribute('aria-label',light?'Switch to black theme':'Switch to white theme');$('theme-toggle').title=light?'Switch to black theme':'Switch to white theme';if(scene){scene.background.set(light?'#fafafa':'#0b0c0e');scene.fog.color.copy(scene.background)}if(deviceView)deviceView.scene.background.set(light?'#f6f6f5':'#101112')}
$('theme-toggle').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'dark':'light';try{localStorage.setItem('flowguard-theme',document.documentElement.dataset.theme)}catch(e){}applyTheme()});applyTheme();
function setSceneControls(enabled){for(const el of document.querySelectorAll('#app button, #app select, #app input')){if(['mobile-tools','mobile-status','close-tools','close-insight','story-toggle','theme-toggle'].includes(el.id)||el.closest('#error')||el.id==='close-device')continue;el.disabled=!enabled}}
function showGraphicsError(message){ready=false;cancelAnimationFrame(frameHandle);setSceneControls(false);$('loading').hidden=true;$('error').hidden=false;$('error-message').textContent=message;$('markers').hidden=true;$('story').hidden=true;$('alert-banner').hidden=true;$('insight').hidden=true;closeInspector();if($('device-dialog').open)$('device-dialog').close()}
function closeMobilePanels(){document.body.classList.remove('mobile-tools-open','mobile-status-open','caption-expanded');$('mobile-tools').setAttribute('aria-expanded','false');$('mobile-status').setAttribute('aria-expanded','false');$('story-toggle').setAttribute('aria-expanded','false');if(mobile()){$('layers-panel').hidden=true;$('layers-btn').setAttribute('aria-expanded','false')}}
$('mobile-tools').addEventListener('click',()=>{const open=!document.body.classList.contains('mobile-tools-open');closeMobilePanels();closeInspector();document.body.classList.toggle('mobile-tools-open',open);$('layers-panel').hidden=!open;$('mobile-tools').setAttribute('aria-expanded',String(open));});
$('mobile-status').addEventListener('click',()=>{const open=!document.body.classList.contains('mobile-status-open');closeMobilePanels();closeInspector();document.body.classList.toggle('mobile-status-open',open);$('mobile-status').setAttribute('aria-expanded',String(open));});
$('close-tools').addEventListener('click',closeMobilePanels);
$('close-insight').addEventListener('click',closeMobilePanels);
$('story-toggle').addEventListener('click',()=>{const expanded=document.body.classList.toggle('caption-expanded');$('story-toggle').setAttribute('aria-expanded',String(expanded));});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMobilePanels()});
function layoutPanels(){const header=document.querySelector('header'),base=$('app').getBoundingClientRect().top;const bottom=Math.max(...[...header.children].map(el=>el.getBoundingClientRect().bottom));$('app').style.setProperty('--header-bottom',Math.ceil(bottom-base+8)+'px');const caption=mobile()&&!$('story').hidden?Math.min($('story').getBoundingClientRect().height,100):0;$('app').style.setProperty('--caption-height',caption+'px');resize();}
const layoutObserver=new ResizeObserver(layoutPanels);layoutObserver.observe(document.querySelector('header'));layoutObserver.observe($('story'));layoutObserver.observe($('app'));
window.addEventListener('resize',layoutPanels);layoutPanels();
setSceneControls(false);
init().catch(error=>{console.error(error);showGraphicsError('The 3D scene could not load. Check your connection and use a browser with WebGL 2 available, then try again.')});
